### ISSUE TITLE
Try to Pull the image via Docker. Had Install Docker successfully but I got the Permission denied

### ISSUE THREAD

**Issue by tobiasonkes** [rameau-fr/MC-Calib#15]
docker pull frameau/opencv-ceres
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=frameau%2Fopencv-ceres&tag=latest": dial unix /var/run/docker.sock: connect: permission denied

**Comment by BAILOOL** [comment]
@tobiasonkes thank you for the interest in MC-Calib. Might this issue be related to a lack of permissions? https://stackoverflow.com/questions/51342810/how-to-fix-dial-unix-var-run-docker-sock-connect-permission-denied-when-gro

**Comment by tobiasonkes** [comment]
Thank you. Yeah this was the Problem
