### ISSUE TITLE
what does the resolution of the boards mean? 

### ISSUE THREAD

**Issue by hding2455** [rameau-fr/MC-Calib#31]
what does the resolution of the boards mean?

**Comment by rameau-fr** [comment]
Hello,
Thank you very much for your interest in MC-Calib, and sorry for this very delayed response. I am just back from my annual leave!

The "x and y resolution" is just setting the image resolution for the boards to be printed. If you want to generate a very high-resolution image, you can adjust this parameter. So it is important just to create the boards, but it will have no incidence for the calibration itself.
