### ISSUE TITLE
cmake question (anxious)

### ISSUE THREAD

**Issue by UselessHua** [rameau-fr/MC-Calib#46]
![image](https://github.com/rameau-fr/MC-Calib/assets/125537232/58c299b9-e613-4fd5-a313-70ed3ee07bcf)
How to solve this problem and how to find McCalib?

**Comment by pedroarroyo** [comment]
If it helps, I am also seeing this on Ubunty 20.04.

**Comment by rameau-fr** [comment]
Thank you very much for the additional feedback. Could you please share the entire error message? I will try to replicate it but I assume it is a problem with libraries versions. If possible could you report the version of all your dependencies ? An easy fix is to use the docker provided with MC-Calib (if you are familiar with it).

**Comment by vswdigitall** [comment]
I can comment line and it works.

**Comment by BAILOOL** [comment]
@vswdigitall please follow the issue template so we can better understand your setup and resolve the issue faster.

What's on the line `CMakeLists.txt:51`? I believe CMakeLists.txt has been modified in your case compared to the one found in `master` branch?

**Comment by vswdigitall** [comment]
For current master, i can't cmake your code. Only if disable line 74 it works. 
Line 51 solved by installing doxygen.

**Comment by BAILOOL** [comment]
Please provide the full output from the cmake command to start with @vswdigitall

**Comment by vswdigitall** [comment]
cmake ..

**Comment by BAILOOL** [comment]
@nukbridge thank you for providing the solution.
