### ISSUE TITLE
Printing Board Questions

### ISSUE THREAD

**Issue by jakefoehner** [rameau-fr/MC-Calib#54]
### System information (version)

* Operating System / Platform => ❔
* OpenCV => ❔
* Ceres => ❔
* Boost => ❔
* C++ => ❔
* Compiler => ❔

### Vision system

* Number of cameras => ❔
* Types of cameras => ❔ (perspective, fisheye, hybrid)
* Multicamera configurations => ❔ (overlapping, non-overlapping, converging)
* Configuration file => ❔ (i.e. `*.yml`)
* Image sequences => ❔
    - number of images per camera
    - if relevant and possible, please share image sequences

### Describe the issue / bug

Please provide a clear and concise description of what the issue / bug is.

Hi,

I am planning on printing a charuco board. I was curious if there is an optimal number of squares to generate with? I was planning on doing 6x9. Also 6x9 is the size ratio of the poster we are printing on, but the board is generated with white space on the sides with those specs. Is it okay to crop out that white space?

**Comment by rameau-fr** [comment]
Thank you very much for your message. It is a complicated question as it mostly depends on your setup. 
For instance, for large field-of-view cameras and/or if the boards have to be placed far away from the cameras, then I would recommend sacrificing the number of squares to make the Aruco marker easier to detect. If you have a narrow FoV and if you cannot see the entire board at once, then I would probably recommend using a large number of squares. 
Regarding cropping, it is entirely okay as long as you preserve the aspect ratio (the squares still have to be squares).
Please make sure to generate your board directly using the toolbox as the Charcuco board you can find elsewhere might be incompatible.
