### ISSUE TITLE
other patterns

### ISSUE THREAD

**Issue by maryam-saeedi** [rameau-fr/MC-Calib#72]
Hi, I would like to check whether it is possible to calibrate cameras with simple checkerboard pattern or not? If so, how should we change the config file?

**Comment by rameau-fr** [comment]
Hello, thank you very much for your interest in this project.
Currently, MC-Calib is exclusively compatible with patterns generated via the toolbox itself. You cannot use calibration patterns from other sources such as AprilTag or calib.io, as it is incompatible with those. Additionally, it is not compatible with simple calibration boards, as knowing the respective identification of the boards is important for complex multi-camera setups.
