### ISSUE TITLE
main_display_cam_obj_pose.py error

### ISSUE THREAD

**Issue by naivenaive** [rameau-fr/MC-Calib#73]
Thanks for your excellent work. When I try to show camera and object pose using main_display_cam_obj_pose.py, an error occured. 
```
 File "python_utils/main_display_cam_obj_pose.py", line 140, in <module>
    Pts3d = np.dot(obj_mat.T,R.T) + T
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (32,5) and (3,3) not aligned: 5 (dim 1) != 3 (dim 0)
```
Would you please help fix this error? Thanks.

**Comment by rameau-fr** [comment]
Thank you very much for your feedback. Would it be possible to share your calibration results with us so that we can try to analyze and find the source of the error?
