### ISSUE TITLE
Documentation for docker image run

### ISSUE THREAD

**Issue by amy-tabb** [rameau-fr/MC-Calib#75]
### System information (version)

* Operating System / Platform => ❔Ubuntu 22.04
* OpenCV => n/a
* Ceres => n/a
* Boost => n/a
* C++ => n/a
* Compiler => n/a

### Vision system

Intend to run some of your real or synthetic sequences

### Describe the issue / bug

I would like to run MC-Calib from your provided docker image and am able to pull it from the docker hub. The following is in the README -- 

'''bash
docker run \
            -ti --rm \
            --volume="${PWD}:/home/MC-Calib" \
            --volume="PATH_TO_DATA:/home/MC-Calib/data" \
            bailool/mc-calib-prod
'''

What do the two bindmounts refer to? I could find something related to '--volume="PATH_TO_DATA:/home/MC-Calib/data"' in the documentation for running 'calibrate', but could not find what '--volume="${PWD}:/home/MC-Calib" ' needs to contain or this directory's function. Thank you.

**Comment by BAILOOL** [comment]
Hi @amy-tabb. Thank you for your interest in the MC-Calib.

I have improved the documentation in this change https://github.com/rameau-fr/MC-Calib/pull/76 

```bash
docker run \
            -ti --rm \
            --volume="$PATH_TO_REPO_ROOT:/home/MC-Calib" \
            --volume="$PATH_TO_DATA:/home/MC-Calib/data" \
            bailool/mc-calib-prod
```

Let me know if this works for you.

**Comment by amy-tabb** [comment]
Awesome, yes that answers my question, thank you @BAILOOL !
